// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaWM6sTjKeQmElNM26BgDA3s2mNXFFz7U',
    appId: '1:621851175504:web:e8173fc0e5aeaec3233f55',
    messagingSenderId: '621851175504',
    projectId: 'flutter-mobil-application',
    authDomain: 'flutter-mobil-application.firebaseapp.com',
    storageBucket: 'flutter-mobil-application.firebasestorage.app',
    measurementId: 'G-EG253R7ZTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2dPLN2vD5dJhtc_OasXJcMPgfpXi_P4g',
    appId: '1:621851175504:android:6895392a2f0c81aa233f55',
    messagingSenderId: '621851175504',
    projectId: 'flutter-mobil-application',
    storageBucket: 'flutter-mobil-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsNPcZsWoCOKKyg446GfjxB_lOS0j8rqU',
    appId: '1:621851175504:ios:c6d4137b01ec4171233f55',
    messagingSenderId: '621851175504',
    projectId: 'flutter-mobil-application',
    storageBucket: 'flutter-mobil-application.firebasestorage.app',
    iosBundleId: 'com.example.fristMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsNPcZsWoCOKKyg446GfjxB_lOS0j8rqU',
    appId: '1:621851175504:ios:c6d4137b01ec4171233f55',
    messagingSenderId: '621851175504',
    projectId: 'flutter-mobil-application',
    storageBucket: 'flutter-mobil-application.firebasestorage.app',
    iosBundleId: 'com.example.fristMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaWM6sTjKeQmElNM26BgDA3s2mNXFFz7U',
    appId: '1:621851175504:web:a4af498dc653ccec233f55',
    messagingSenderId: '621851175504',
    projectId: 'flutter-mobil-application',
    authDomain: 'flutter-mobil-application.firebaseapp.com',
    storageBucket: 'flutter-mobil-application.firebasestorage.app',
    measurementId: 'G-BSFM4XEK9B',
  );
}
